version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(ci): "
    labels:
      - dependencies
      - github_actions

  - package-ecosystem: gomod
    directories:
      - /
      - /src/*
    schedule:
      interval: daily
    commit-message:
      prefix: "deps(go): "
    labels:
      - dependencies
      - go
    groups:
      resty:
        patterns:
          - github.com/go-resty/resty/v2
      testify:
        patterns:
          - github.com/stretchr/testify

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps(docker): "
    labels:
      - dependencies
      - docker
